---
name: Docker Build
on: # yamllint disable-line rule:truthy
  pull_request:
    branches: ["dev", "develop", "main", "master"]
    paths: [docker/infra/**]
  # to have an ability to run thee workflow manually
  workflow_dispatch: # yamllint disable-line rule:empty-values
#
permissions:
  contents: read
  id-token: write
#
jobs:
  build:
    name: go-sdk-tests
    env:
      ARTIFACT_REGISTRY_URL: europe-west1-docker.pkg.dev
      GCP_PROJECT_ID_MGMT: ${{ secrets.GCP_PROJECT_ID_MGMT }}
      IMAGE_NAME: go-sdk-tests
    runs-on: ubuntu-latest

    steps:
      - name: actions/checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1 - https://github.com/actions/checkout/releases

      - name: setup/env
        id: setup_env_vars
        run: |
          echo "NOW=$(date -u +%Y-%m-%dT%H:%M:%S)" >> "${GITHUB_ENV}"
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> "${GITHUB_ENV}"
          echo "VERSION=$(cat docker/infra/.version)" >> "${GITHUB_OUTPUT}"

      - name: docker/setup-buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0 - https://github.com/docker/setup-buildx-action/releases
        id: buildx

      - name: gcloud/auth
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0 - https://github.com/google-github-actions/auth/releases
        id: authentication
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_MGMT }}
          service_account: github@${{ env.GCP_PROJECT_ID_MGMT }}.iam.gserviceaccount.com

      - name: docker/login
        run: |
          gcloud auth configure-docker ${{ env.ARTIFACT_REGISTRY_URL }} -q

      - name: docker/build & push
        run: |-
          cd docker/infra
          docker buildx build --push \
          --tag "${{ env.ARTIFACT_REGISTRY_URL }}/${{ env.GCP_PROJECT_ID_MGMT }}/indykite/${{ env.IMAGE_NAME }}":latest \
          --tag "${{ env.ARTIFACT_REGISTRY_URL }}/${{ env.GCP_PROJECT_ID_MGMT }}/indykite/${{ env.IMAGE_NAME }}":"${{ steps.setup_env_vars.outputs.VERSION }}" \
          --platform linux/amd64,linux/arm64,linux/arm/v7 .
